[build-system]
requires = [ "setuptools" ]
build-backend = "setuptools.build_meta"

[project]
name = "my-tool"
description = "my tool"
version = "1.0.0"
dependencies = [
  "requests",
  "click @ git+https://github.com/pallets/click.git@main"
]

[project.scripts]
my-tool = "my_tool:main"
