[book]
authors = ["Yusuf Bera Ertan"]
language = "en"
multilingual = false
src = "src"
title = "dream2nix documentation"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
additional-css = ["theme/highlight-dark.css"]
