
[project]
name = "dream2nix_docs"
description = "documentation of dream2nix"
authors = [{ name = "David Hauer"}, {name = "Paul Haerle", email = "hello@phaer.org"}]
dynamic = ["version"]
dependencies = ["mkdocs"]


[tool.setuptools]
packages = [ "dream2nix_docs" ]
