name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: '15 18 * * *' # runs daily at 18:15 UTC

jobs:
  lockfile:
    strategy:
      matrix:
        flake-dir: [ ".", "./dev-flake" ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update nixpkgs"
          pr-labels: dependencies
          inputs: nixpkgs
          path-to-flake-dir: ${{ matrix.flake-dir }}
