name: "Test dream2nix"
on:
  pull_request:
  push:

jobs:

  tests-pure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: cachix/install-nix-action@v22
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/8i0c4nnvddybdq6a684ffybc5p7ziif0/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          max-jobs = 10
    - uses: cachix/cachix-action@v12
      with:
        name: nix-community
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: |
        nix flake check

  tests-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: cachix/install-nix-action@v22
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/8i0c4nnvddybdq6a684ffybc5p7ziif0/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          max-jobs = 10
    - uses: cachix/cachix-action@v12
      with:
        name: nix-community
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix run .#format -- --fail-on-change
